In [1]:
import numpy as np
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [2]:
np.random.rand(3,2)

array([[0.17905895, 0.22011941],
       [0.44658735, 0.93722288],
       [0.43327035, 0.80115933]])

In [6]:
s1 = np.arange(20)
s1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [8]:
s1.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [9]:
import pandas as pd


In [17]:
ex1 = pd.DataFrame({'Product' : ['a', 'b', 'c', 'd'] , 'Sales' : [1000,2000,3000,8999]})
print(ex1)

  Product  Sales
0       a   1000
1       b   2000
2       c   3000
3       d   8999


In [23]:
import os

In [27]:
os.getcwd()

'C:\\Users\\Dell'

In [31]:
os.chdir('D:\\Python Programming\\Data')


In [32]:
os.getcwd()

'D:\\Python Programming\\Data'

In [37]:
df = pd.read_csv('LGD.csv')
df

Ac_No  Age  Years of Experience  Number of Vehicles Gender   Married  \
0      150024   24                    5                   1      M   Married   
1      144880   31                   10                   1      F    Single   
2      133742   56                   37                   1      M   Married   
3      151282   52                   31                   1      F   Married   
4      174407   20                    3                   1      M    Single   
...       ...  ...                  ...                 ...    ...       ...   
15285  189499   61                   43                   4      F  Divorced   
15286  142111   69                   48                   4      F  Divorced   
15287  176444   69                   51                   4      F  Divorced   
15288  180420   22                    4                   4      M  Divorced   
15289  157201   20                    2                   4      F  Divorced   

       Losses in Thousands Acct_Open_Dt   Defaulted  
0               203.319595   22-07-2019  22-12-2019  
1               402.197302   21-07-2019  21-12-2019  
2               553.132096   20-07-2019  20-12-2019  
3               292.430579   19-07-2019  19-12-2019  
4               246.540576   18-07-2019  18-12-2019  
...                    ...          ...         ...  
15285            58.426429   16-09-1978  16-09-1980  
15286           304.519134   15-09-1978  15-09-1980  
15287           282.149148   14-09-1978  14-09-1980  
15288           822.470554   13-09-1978  13-09-1980  
15289           406.924740   12-09-1978  12-09-1980  

[15290 rows x 9 columns]

In [38]:
type(df)

pandas.core.frame.DataFrame

In [40]:
df.head(10)

Ac_No  Age  Years of Experience  Number of Vehicles Gender  Married  \
0  150024   24                    5                   1      M  Married   
1  144880   31                   10                   1      F   Single   
2  133742   56                   37                   1      M  Married   
3  151282   52                   31                   1      F  Married   
4  174407   20                    3                   1      M   Single   
5  142548   29                    8                   1      M  Married   
6  183396   36                   19                   1      F   Single   
7  106838   67                   49                   1      F  Married   
8  137434   69                   48                   1      M   Single   
9  192628   16                    0                   1      F   Single   

   Losses in Thousands Acct_Open_Dt   Defaulted  
0           203.319595   22-07-2019  22-12-2019  
1           402.197302   21-07-2019  21-12-2019  
2           553.132096   20-07-2019  20-12-2019  
3           292.430579   19-07-2019  19-12-2019  
4           246.540576   18-07-2019  18-12-2019  
5           384.676395   17-07-2019  17-12-2019  
6           462.158856   16-07-2019  16-12-2019  
7           168.934036   15-07-2019  15-12-2019  
8            69.893041   14-07-2019  14-12-2019  
9           242.772576   13-07-2019  13-12-2019

In [41]:
df.tail(10)

Ac_No  Age  Years of Experience  Number of Vehicles Gender   Married  \
15280  169309   47                   26                   4      M  Divorced   
15281  102285   17                    0                   4      F  Divorced   
15282  175296   30                   11                   4      M  Divorced   
15283  140800   52                   31                   4      F  Divorced   
15284  176376   36                   19                   4      M  Divorced   
15285  189499   61                   43                   4      F  Divorced   
15286  142111   69                   48                   4      F  Divorced   
15287  176444   69                   51                   4      F  Divorced   
15288  180420   22                    4                   4      M  Divorced   
15289  157201   20                    2                   4      F  Divorced   

       Losses in Thousands Acct_Open_Dt   Defaulted  
15280           327.005494   21-09-1978  21-09-1980  
15281           376.158182   20-09-1978  20-09-1980  
15282           472.252075   19-09-1978  19-09-1980  
15283           666.040877   18-09-1978  18-09-1980  
15284           204.462118   17-09-1978  17-09-1980  
15285            58.426429   16-09-1978  16-09-1980  
15286           304.519134   15-09-1978  15-09-1980  
15287           282.149148   14-09-1978  14-09-1980  
15288           822.470554   13-09-1978  13-09-1980  
15289           406.924740   12-09-1978  12-09-1980

In [42]:
df[9:20]

Ac_No  Age  Years of Experience  Number of Vehicles Gender  Married  \
9   192628   16                    0                   1      F   Single   
10  154894   19                    1                   1      M   Single   
11  187293   29                    8                   1      F   Single   
12  173214   20                    1                   1      F  Married   
13  163905   67                   49                   1      M  Married   
14  157356   46                   27                   1      M  Married   
15  160387   57                   40                   1      M  Married   
16  127360   65                   48                   1      M   Single   
17  108345   20                    1                   1      M   Single   
18  122164   67                   49                   1      M   Single   
19  103555   62                   45                   1      M  Married   

    Losses in Thousands Acct_Open_Dt   Defaulted  
9            242.772576   13-07-2019  13-12-2019  
10           763.729857   12-07-2019  12-12-2019  
11           407.389374   11-07-2019  11-12-2019  
12           161.579521   10-07-2019  10-12-2019  
13           242.888776   09-07-2019  09-12-2019  
14           358.521705   08-07-2019  08-12-2019  
15           314.662097   07-07-2019  07-12-2019  
16           306.739501   06-07-2019  06-12-2019  
17           772.644820   05-07-2019  05-12-2019  
18           593.427411   04-07-2019  04-12-2019  
19           275.214409   03-07-2019  03-12-2019

In [43]:
df.iloc[9:20,0:3]

Ac_No  Age  Years of Experience
9   192628   16                    0
10  154894   19                    1
11  187293   29                    8
12  173214   20                    1
13  163905   67                   49
14  157356   46                   27
15  160387   57                   40
16  127360   65                   48
17  108345   20                    1
18  122164   67                   49
19  103555   62                   45

In [46]:
df.loc[9:20,['Ac_No', 'Age']]

Ac_No  Age
9   192628   16
10  154894   19
11  187293   29
12  173214   20
13  163905   67
14  157356   46
15  160387   57
16  127360   65
17  108345   20
18  122164   67
19  103555   62
20  165177   44

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15290 entries, 0 to 15289
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Ac_No                15290 non-null  int64  
 1   Age                  15290 non-null  int64  
 2   Years of Experience  15290 non-null  int64  
 3   Number of Vehicles   15290 non-null  int64  
 4   Gender               15290 non-null  object 
 5   Married              15290 non-null  object 
 6   Losses in Thousands  15290 non-null  float64
 7   Acct_Open_Dt         15290 non-null  object 
 8   Defaulted            15290 non-null  object 
dtypes: float64(1), int64(4), object(4)
memory usage: 1.1+ MB


In [48]:
df['Married'].nunique()

3

In [49]:
df['Gender'].nunique()

2

In [51]:
df['Gender'].value_counts()


F    7747
M    7543
Name: Gender, dtype: int64

In [54]:
data4 = df[df['Gender']=='M']


In [55]:
data4['Gender'].unique()

array(['M'], dtype=object)

In [56]:
data4['Gender'].value_counts()

M    7543
Name: Gender, dtype: int64

In [57]:
data5 = df[df['Gender']!='M']

In [58]:
data5['Gender'].value_counts()

F    7747
Name: Gender, dtype: int64

In [60]:
data6 = df[(df['Gender']=='M') & (df['Age'] > 30)]

In [61]:
data6['Gender'].value_counts()

M    4827
Name: Gender, dtype: int64

In [62]:
np.min(data6['Age'])

31

In [64]:
data7 = df[df['Age'].isin([31,32])]

In [65]:
data7['Age'].unique()

array([31, 32], dtype=int64)

In [68]:
data8 = df[(df['Gender']=='M') & (df['Age'].isin([31,32]))]

In [69]:
pd.crosstab(data8.Gender, data8.Age)

Age     31  32
Gender        
M       91  82